Fix NFS silly-renamed files bug
If store/ is a NFS mount, then deleting unclosed files results in so
called "silly-renamed" files [1].

Marv calls shutil.rmtree on a diretory which in turn deletes all its
files. Since Marv doesn't close its open files before shutil.rmtree, the
file will not actually be deleted but renamed. Thus the call to os.rmdir
inside shutil.rmtree [2] will fail, since the to-be-deleted folder now
contains at lesat one silly-renamed file.

This bug will manifest itself during `marv run` like this:

```
2019-07-30 14:23:59,387 ERRO marv.cli Exception occured for dataset ibziee99w7znulou6qstnzpgti:
Traceback (most recent call last):
  File "/home/marv/code/marv/marv/cli.py", line 433, in marvcli_run
    excluded_nodes, cachesize=cachesize)
  File "/home/marv/code/marv/marv/site.py", line 401, in run
    shutil.rmtree(tmpdir)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/site/store/ibziee99w7znulou6qstnzpgti/.bagmeta-1'
2019-07-30 14:23:59,388 ERRO marv.cli Error occured for dataset ibziee99w7znulou6qstnzpgti: [Errno 39] Directory not empty: '/site/store/ibziee99w7znulou6qstnzpgti/.bagmeta-1'
```

Furthermore, when starting `marv run` with the environment `PDB=1`, we
can observe the following state:

```
(Pdb++) names
[u'default-stream']
(Pdb++) import os.path
(Pdb++) os.path.isfile(fullname)
False
(Pdb++) os.listdir(path)
[u'.nfs00000000000219f900001b69']
```

Which confirms that the file .bagmeta-1/default-stream was indeed
renamed to .bagmeta-1/.nfs00000000000219f900001b69

[1]: http://nfs.sourceforge.net/#faq_d2
[2]: https://github.com/python/cpython/blob/2.7/Lib/shutil.py#L277